### ISSUE TITLE
V2 Todo en vrac

### ISSUE THREAD

**Issue by brunob** [geodiversite/geodiversite#14]
- [x] **rétablir la possibilité de modifier le titre** d'un media (dans la v1 le crayon était sur le titre dans le fil d'ariane)
- [ ] vérifier que l'attribution auto des squelettes pour les pages uniques https://github.com/geodiversite/geodiversite/blob/master/geol_pipelines.php#L39 fonctionne bien sans le plugin compositions, sinon ajouter celui-ci en necessite
- [x] revoir tout le source pour utiliser des balises HTML5
    - [x] remplacer les dates qui utilisent des balises abbr par des time
    - [x] utiliser des balises meta dans le bloc media_infopubli
    - [x] ~~activer le html5 dans le public avec `$GLOBALS['meta']['version_html_max'] = 'html5';` dans les options~~ => plus besoin de ça en SPIP 4
- [x] reprendre les vignettes de https://github.com/geodiversite/geodiversite/tree/master/prive/vignettes pour les agrandir à 640px de large
- [x] page rubrique : passer le filtre de la liste des catégories dans un simple select au dessus de la grille de medias (?)
- [x] utiliser photoswipe pour le zoom dans les images
    - [x] ajouter photoswipe dans https://github.com/geodiversite/geodiversite_install_sh/blob/master/install_geodiversite.sh & https://github.com/geodiversite/geodiversite_install/blob/master/paquet.xml#L28
